export interface FlagState {
  code: string;
  name: string;
  flag: string;
  lat: number;
  lng: number;
  regulation: string;
  authority: string;
  standardKey: string;
  chestCategories: string[];
  inspectionInterval: string;
  keyDocuments: string[];
  authorityUrl: string;
  details: string;
}

export const flagStates: FlagState[] = [
  {
    code: 'PA',
    name: 'Panama',
    flag: '\u{1F1F5}\u{1F1E6}',
    lat: 9.0,
    lng: -79.5,
    regulation: 'Merchant Marine Circular MMC-155',
    authority: 'Panama Maritime Authority (AMP)',
    standardKey: 'PMA-MMC-155',
    chestCategories: ['Category A - Ocean-going vessels', 'Category B - Coastal vessels', 'Category C - Port/harbor vessels'],
    inspectionInterval: 'Annual inspection required',
    keyDocuments: ['MMC-155 Medical Equipment Requirements', 'STCW Medical First Aid Training', 'ILO MLC 2006 Compliance'],
    authorityUrl: 'https://amp.gob.pa',
    details: 'Panama requires medical chests categorized by vessel type and trading area. Category A vessels (unlimited trading) must carry the most comprehensive medical supplies including controlled substances. All medications must be clearly labeled in English and Spanish.',
  },
  {
    code: 'LR',
    name: 'Liberia',
    flag: '\u{1F1F1}\u{1F1F7}',
    lat: 6.4,
    lng: -9.4,
    regulation: 'Marine Notice MLC-003 Rev. 2',
    authority: 'Liberian Maritime Authority (LiMA)',
    standardKey: 'LIMA-MLC003',
    chestCategories: ['Scale I - International voyages', 'Scale II - Near-coastal voyages', 'Scale III - Harbor/inland'],
    inspectionInterval: 'Annual inspection, quarterly self-checks',
    keyDocuments: ['Marine Notice MLC-003', 'Medical Stores Scale I/II/III Lists', 'Controlled Substances Authorization Form'],
    authorityUrl: 'https://www.liscr.com',
    details: 'Liberia follows ILO MLC 2006 guidelines closely. Medical stores must be inspected annually by a qualified pharmacist or medical practitioner. Vessels must maintain a Medicine Chest Inspection Certificate valid for 12 months.',
  },
  {
    code: 'MH',
    name: 'Marshall Islands',
    flag: '\u{1F1F2}\u{1F1ED}',
    lat: 7.1,
    lng: 171.2,
    regulation: 'Marine Notice MI-108 Rev. 4',
    authority: 'Republic of the Marshall Islands (RMI)',
    standardKey: 'RMI-MI108',
    chestCategories: ['Category A - Unlimited voyages', 'Category B - Near-coastal', 'Category C - Sheltered waters'],
    inspectionInterval: 'Annual inspection required',
    keyDocuments: ['MI-108 Medical Stores Requirements', 'MN-7-042 Medical Fitness Certificates', 'Approved Medical Chest Supplier List'],
    authorityUrl: 'https://www.register-iri.com',
    details: 'RMI requires all vessels to carry medical stores appropriate to their trading area. Medical chests must be supplied and inspected by RMI-approved suppliers. The Medical Stores Certificate must be carried onboard.',
  },
  {
    code: 'BS',
    name: 'Bahamas',
    flag: '\u{1F1E7}\u{1F1F8}',
    lat: 25.0,
    lng: -77.4,
    regulation: 'Bahamas Maritime Authority Bulletin 158',
    authority: 'Bahamas Maritime Authority (BMA)',
    standardKey: 'BMA-B158',
    chestCategories: ['Category A - All waters', 'Category B - Restricted areas', 'Category C - Near-coastal'],
    inspectionInterval: 'Annual inspection by approved supplier',
    keyDocuments: ['BMA Bulletin 158 Medical Stores', 'BMA Medical Scales A/B/C', 'BMA Approved Service Providers'],
    authorityUrl: 'https://www.bahamasmaritime.com',
    details: 'The Bahamas Maritime Authority requires medical stores based on vessel type, crew size, and trading area. All pharmaceutical items must have a minimum 12-month shelf life at time of supply.',
  },
  {
    code: 'MT',
    name: 'Malta',
    flag: '\u{1F1F2}\u{1F1F9}',
    lat: 35.9,
    lng: 14.5,
    regulation: 'EU Directive 92/29/EEC & Merchant Shipping Rules',
    authority: 'Transport Malta',
    standardKey: 'TM-EU92',
    chestCategories: ['Category A - Unlimited navigation', 'Category B - Less than 175 nm from port', 'Category C - Port operations/coastal'],
    inspectionInterval: 'Annual inspection, 5-year renewal',
    keyDocuments: ['S.L. 234.46 Medical Stores Rules', 'EU Directive 92/29/EEC Annex I & II', 'Transport Malta Circular 60/2019'],
    authorityUrl: 'https://www.transport.gov.mt',
    details: 'Malta follows EU Directive 92/29/EEC for medical supplies on board vessels. Three categories of medical chest are defined based on the vessel distance from qualified medical care. Anti-malarial medications required for tropical voyages.',
  },
  {
    code: 'CY',
    name: 'Cyprus',
    flag: '\u{1F1E8}\u{1F1FE}',
    lat: 35.1,
    lng: 33.4,
    regulation: 'Merchant Shipping (Medical Stores) Rules 2015',
    authority: 'Dept. of Merchant Shipping Cyprus',
    standardKey: 'DMS-CY-2015',
    chestCategories: ['Category A - Unlimited voyages', 'Category B - Less than 175 nm', 'Category C - Coastal/harbor'],
    inspectionInterval: 'Annual inspection required',
    keyDocuments: ['Cyprus Medical Stores Rules 2015', 'EU Directive 92/29/EEC Implementation', 'DMS Circular 14/2015'],
    authorityUrl: 'https://www.dms.gov.cy',
    details: 'Cyprus implements EU Directive 92/29/EEC with additional national requirements. Medical chests must be inspected by approved service providers. Vessels carrying dangerous goods need additional antidotes.',
  },
  {
    code: 'NO',
    name: 'Norway',
    flag: '\u{1F1F3}\u{1F1F4}',
    lat: 60.5,
    lng: 8.5,
    regulation: 'FOR-2001-03-09 No. 439 (Medical Equipment Regulations)',
    authority: 'Norwegian Maritime Authority (NMA)',
    standardKey: 'NMA-FOR439',
    chestCategories: ['Category 1 - Ocean-going ships', 'Category 2 - Ships in European trade', 'Category 3 - Coastal vessels', 'Category 4 - Fishing vessels'],
    inspectionInterval: 'Annual inspection by approved pharmacy',
    keyDocuments: ['FOR-2001-03-09-439 Full Regulation', 'NMA Approved Pharmacy List', 'Medical Equipment Annex A/B/C/D'],
    authorityUrl: 'https://www.sdir.no',
    details: 'Norway has one of the most detailed maritime medical regulations in Europe with four categories. Medical chests must be inspected by NMA-approved pharmacies. Norwegian requirements often exceed EU minimum standards.',
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    flag: '\u{1F1EC}\u{1F1E7}',
    lat: 51.5,
    lng: -0.1,
    regulation: 'MSN 1768 (M+F) Ship Medical Stores',
    authority: 'Maritime and Coastguard Agency (MCA)',
    standardKey: 'MCA-MSN1768',
    chestCategories: ['Category A - Unlimited voyages', 'Category B - Within 150 nm', 'Category C - Within 25 nm/inland'],
    inspectionInterval: 'Annual inspection required',
    keyDocuments: ['MSN 1768 (M+F) Amendment 3', 'MGN 261 (M+F) Ships Medical Stores', 'Merchant Shipping Medical Stores Regulations 1995'],
    authorityUrl: 'https://www.gov.uk/mca',
    details: 'The UK MCA requires medical stores per MSN 1768 with three categories based on trading area. Controlled drugs require Home Office authorization. The Ship Captain Medical Guide (SCMG) must be carried onboard. Post-Brexit, UK requirements have diverged slightly from EU standards.',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    flag: '\u{1F1F3}\u{1F1F1}',
    lat: 52.4,
    lng: 4.9,
    regulation: 'Besluit Medische Uitrusting aan Boord van Schepen',
    authority: 'Human Environment and Transport Inspectorate (ILT)',
    standardKey: 'ILT-BMU',
    chestCategories: ['Category A - Unlimited voyages', 'Category B - Within 175 nm', 'Category C - Coastal/harbor'],
    inspectionInterval: 'Annual inspection by approved supplier',
    keyDocuments: ['Besluit Medische Uitrusting (BMU)', 'Regeling Medische Uitrusting', 'ILT Approved Supplier List'],
    authorityUrl: 'https://www.ilent.nl',
    details: 'The Netherlands implements EU Directive 92/29/EEC through national legislation. Medical chests must be supplied and inspected by ILT-approved suppliers. Dutch requirements include additional provisions for narcotic substances, requiring a separate DEA-equivalent authorization.',
  },
  {
    code: 'GR',
    name: 'Greece',
    flag: '\u{1F1EC}\u{1F1F7}',
    lat: 37.9,
    lng: 23.7,
    regulation: 'Presidential Decree 376/1995 (as amended)',
    authority: 'Hellenic Coast Guard',
    standardKey: 'HCG-PD376',
    chestCategories: ['Category A - Unlimited voyages', 'Category B - Near-coastal', 'Category C - Harbor vessels'],
    inspectionInterval: 'Annual inspection required',
    keyDocuments: ['PD 376/1995 Medical Equipment', 'EU Directive 92/29/EEC Greek Implementation', 'HCG Circular on Medical Stores'],
    authorityUrl: 'https://www.hcg.gr',
    details: 'Greece, as one of the largest flag states, implements EU medical requirements through PD 376/1995. The Hellenic Coast Guard oversees compliance. Certain medications require Greek-language labeling for vessels with Greek-speaking crew.',
  },
  {
    code: 'SG',
    name: 'Singapore',
    flag: '\u{1F1F8}\u{1F1EC}',
    lat: 1.35,
    lng: 103.8,
    regulation: 'Merchant Shipping (Medical Stores) Rules 2014',
    authority: 'Maritime and Port Authority of Singapore (MPA)',
    standardKey: 'MPA-MSR2014',
    chestCategories: ['Scale A - Unlimited voyages', 'Scale B - Near-coastal trade', 'Scale C - Harbor craft'],
    inspectionInterval: 'Annual inspection, 5-year certificate renewal',
    keyDocuments: ['MS (Medical Stores) Rules 2014', 'MPA Shipping Circular SC18-05', 'MPA Approved Medical Providers List'],
    authorityUrl: 'https://www.mpa.gov.sg',
    details: 'Singapore MPA requires medical stores per three scales. As a major port state, Singapore has stringent requirements. All vessels calling at Singapore are subject to PSC inspections which include medical store checks.',
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    flag: '\u{1F1ED}\u{1F1F0}',
    lat: 22.3,
    lng: 114.2,
    regulation: 'Merchant Shipping (Safety) (Medical Stores) Regulation',
    authority: 'Hong Kong Marine Department',
    standardKey: 'HKMD-MSR',
    chestCategories: ['Scale A - International voyages', 'Scale B - Near-coastal'],
    inspectionInterval: 'Annual inspection by approved pharmacist',
    keyDocuments: ['MS (Safety) (Medical Stores) Regulation', 'Marine Department Notice No. 152', 'Approved Pharmacist List'],
    authorityUrl: 'https://www.mardep.gov.hk',
    details: 'Hong Kong follows UK-derived maritime medical standards with local adaptations. Two scales of medical stores are defined. All medications must have at least 6 months remaining shelf life at time of inspection.',
  },
  {
    code: 'DK',
    name: 'Denmark',
    flag: '\u{1F1E9}\u{1F1F0}',
    lat: 55.7,
    lng: 12.6,
    regulation: 'Order No. 1007 on Medical Equipment on Ships',
    authority: 'Danish Maritime Authority (DMA)',
    standardKey: 'DMA-O1007',
    chestCategories: ['Category A - Unlimited voyages', 'Category B - European waters', 'Category C - Coastal', 'Category CR - Passenger rescue vessels'],
    inspectionInterval: 'Annual inspection by approved pharmacy',
    keyDocuments: ['DMA Order 1007 Medical Equipment', 'DMA Technical Regulation on Medical Stores', 'DMA Approved Pharmacy List'],
    authorityUrl: 'https://www.dma.dk',
    details: 'Denmark has comprehensive medical requirements with four categories. The Danish Maritime Authority requires annual pharmacy inspections. Danish flag vessels must also carry the International Medical Guide for Ships (IMGS).',
  },
  {
    code: 'IT',
    name: 'Italy',
    flag: '\u{1F1EE}\u{1F1F9}',
    lat: 41.9,
    lng: 12.5,
    regulation: 'D.M. 25 May 1988 No. 279 (Medical Equipment)',
    authority: 'Italian Coast Guard / MIT',
    standardKey: 'ICG-DM279',
    chestCategories: ['Category A - Ocean-going vessels', 'Category B - Mediterranean trade', 'Category C - Coastal navigation'],
    inspectionInterval: 'Annual inspection by ASL (Local Health Authority)',
    keyDocuments: ['D.M. 279/1988 Medical Equipment', 'EU Directive 92/29/EEC Italian Implementation', 'ASL Inspection Procedures'],
    authorityUrl: 'https://www.guardiacostiera.gov.it',
    details: 'Italy implements EU requirements through national decree DM 279/1988. Medical stores must be inspected by the local ASL health authority. Italian-language labeling may be required for certain medications.',
  },
  {
    code: 'DE',
    name: 'Germany',
    flag: '\u{1F1E9}\u{1F1EA}',
    lat: 52.5,
    lng: 13.4,
    regulation: 'Verordnung uber die Krankenfursorge auf Kauffahrteischiffen (KrFV)',
    authority: 'BG Verkehr (German Maritime Authority)',
    standardKey: 'BGV-KrFV',
    chestCategories: ['Category A - Unlimited trade', 'Category B - European waters', 'Category C - Coastal/inland'],
    inspectionInterval: 'Annual inspection by approved pharmacy',
    keyDocuments: ['KrFV Medical Stores Regulation', 'BG Verkehr Approved Pharmacy List', 'German Medical Equipment Standards'],
    authorityUrl: 'https://www.bg-verkehr.de',
    details: 'Germany has strict medical equipment requirements enforced by BG Verkehr. Annual inspections must be performed by a BG Verkehr-approved pharmacy. German-language medical guides required for German crew.',
  },
  {
    code: 'CN',
    name: 'China',
    flag: '\u{1F1E8}\u{1F1F3}',
    lat: 39.9,
    lng: 116.4,
    regulation: 'MSA Vessel Inspection Rules - Medical Equipment Chapter',
    authority: 'China Maritime Safety Administration (MSA)',
    standardKey: 'MSA-CN',
    chestCategories: ['Category I - International voyages', 'Category II - Domestic long voyages', 'Category III - Coastal/river'],
    inspectionInterval: 'Annual inspection during vessel survey',
    keyDocuments: ['MSA Medical Equipment Rules', 'GB/T 16857 Medical Equipment Standards', 'CCS Survey Guidelines'],
    authorityUrl: 'https://en.msa.gov.cn',
    details: 'China MSA requires medical stores based on vessel type and trading area. Inspections are typically conducted during annual vessel surveys by CCS (China Classification Society). Chinese-language medication labels required.',
  },
  {
    code: 'JP',
    name: 'Japan',
    flag: '\u{1F1EF}\u{1F1F5}',
    lat: 35.7,
    lng: 139.7,
    regulation: 'Mariners Act Article 81 / Ship Safety Act',
    authority: 'Japan Coast Guard / MLIT',
    standardKey: 'JCG-MA81',
    chestCategories: ['Ocean-going vessels', 'Coastal vessels', 'Fishing vessels'],
    inspectionInterval: 'Annual inspection by designated physician',
    keyDocuments: ['Mariners Act Medical Requirements', 'Ship Safety Act Medical Equipment', 'JCG Medical Stores Guidelines'],
    authorityUrl: 'https://www.mlit.go.jp',
    details: 'Japan requires medical equipment per the Mariners Act and Ship Safety Act. Medical stores must be inspected by designated physicians. Japanese requirements include traditional medicines in addition to Western pharmaceuticals.',
  },
  {
    code: 'IN',
    name: 'India',
    flag: '\u{1F1EE}\u{1F1F3}',
    lat: 20.6,
    lng: 78.9,
    regulation: 'MS (Medical Examination) Rules 2000 / DGS Order 01/2014',
    authority: 'Directorate General of Shipping (DGS)',
    standardKey: 'DGS-01-2014',
    chestCategories: ['Category A - Foreign-going vessels', 'Category B - Home trade vessels', 'Category C - Coastal vessels'],
    inspectionInterval: 'Annual inspection by DGS-approved medical provider',
    keyDocuments: ['DGS Order 01/2014 Medical Stores', 'MS Medical Examination Rules 2000', 'DGS Approved Medical Suppliers'],
    authorityUrl: 'https://www.dgshipping.gov.in',
    details: 'India DGS requires medical stores per vessel category. The DGS maintains a list of approved medical suppliers for Indian flag vessels. Additional anti-malarial medications required for vessels trading in tropical waters.',
  },
  {
    code: 'TR',
    name: 'Turkey',
    flag: '\u{1F1F9}\u{1F1F7}',
    lat: 39.9,
    lng: 32.9,
    regulation: 'Gemiadamlarinin Saglik Durumlarinin Kontrolu ve Saglik Raporu',
    authority: 'General Directorate of Maritime Affairs (GDMA)',
    standardKey: 'GDMA-TR',
    chestCategories: ['Category A - International voyages', 'Category B - Coastal trade', 'Category C - Harbor/inland'],
    inspectionInterval: 'Annual inspection by approved pharmacist',
    keyDocuments: ['GDMA Medical Stores Circular', 'Turkish Maritime Health Regulations', 'Approved Pharmacy List'],
    authorityUrl: 'https://www.uab.gov.tr',
    details: 'Turkey requires medical stores based on vessel trading area and crew size. The General Directorate of Maritime Affairs oversees compliance. Turkish-language medical guides are required. Additional requirements for vessels carrying dangerous cargo.',
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    flag: '\u{1F1E6}\u{1F1EA}',
    lat: 24.5,
    lng: 54.7,
    regulation: 'FTA Maritime Medical Stores Circular 2019',
    authority: 'Federal Transport Authority (FTA)',
    standardKey: 'FTA-UAE-2019',
    chestCategories: ['Category A - International voyages', 'Category B - Regional trade', 'Category C - Coastal/harbor'],
    inspectionInterval: 'Annual inspection by FTA-approved provider',
    keyDocuments: ['FTA Medical Stores Circular 2019', 'UAE Maritime Medical Requirements', 'FTA Approved Service Providers'],
    authorityUrl: 'https://www.fta.gov.ae',
    details: 'The UAE FTA requires medical stores based on voyage type. As a growing flag state, the UAE has modernized its maritime medical requirements. Medical stores must account for extreme heat conditions in the Gulf region.',
  },
];
