export interface FlagState {
  code: string;
  name: string;
  flag: string;
  lat: number;
  lng: number;
  regulation: string;
  authority: string;
  standardKey: string;
}

export const flagStates: FlagState[] = [
  {
    code: 'PA',
    name: 'Panama',
    flag: '\u{1F1F5}\u{1F1E6}',
    lat: 9.0,
    lng: -79.5,
    regulation: 'Medical chest categories A, B, C per Merchant Marine Circular',
    authority: 'Panama Maritime Authority (AMP)',
    standardKey: 'PMA-MMC',
  },
  {
    code: 'LR',
    name: 'Liberia',
    flag: '\u{1F1F1}\u{1F1F7}',
    lat: 6.4,
    lng: -9.4,
    regulation: 'Medical stores per Marine Notice MLC-003',
    authority: 'Liberian Maritime Authority (LiMA)',
    standardKey: 'LIMA-MLC003',
  },
  {
    code: 'MH',
    name: 'Marshall Islands',
    flag: '\u{1F1F2}\u{1F1ED}',
    lat: 7.1,
    lng: 171.2,
    regulation: 'Medical equipment per MI-108 requirements',
    authority: 'Republic of the Marshall Islands (RMI)',
    standardKey: 'RMI-MI108',
  },
  {
    code: 'BS',
    name: 'Bahamas',
    flag: '\u{1F1E7}\u{1F1F8}',
    lat: 25.0,
    lng: -77.4,
    regulation: 'Medical supplies as per Bahamas Maritime Authority Bulletin',
    authority: 'Bahamas Maritime Authority (BMA)',
    standardKey: 'BMA-BULLETIN',
  },
  {
    code: 'MT',
    name: 'Malta',
    flag: '\u{1F1F2}\u{1F1F9}',
    lat: 35.9,
    lng: 14.5,
    regulation: 'EU Directive 92/29/EEC medical requirements',
    authority: 'Transport Malta',
    standardKey: 'TM-EU92',
  },
  {
    code: 'CY',
    name: 'Cyprus',
    flag: '\u{1F1E8}\u{1F1FE}',
    lat: 35.1,
    lng: 33.4,
    regulation: 'Medical stores per EU standards and national regulations',
    authority: 'Dept. of Merchant Shipping Cyprus',
    standardKey: 'DMS-CY',
  },
  {
    code: 'NO',
    name: 'Norway',
    flag: '\u{1F1F3}\u{1F1F4}',
    lat: 60.5,
    lng: 8.5,
    regulation: 'Medical chest categories per FOR-2001-03-09-439',
    authority: 'Norwegian Maritime Authority (NMA)',
    standardKey: 'NMA-FOR439',
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    flag: '\u{1F1EC}\u{1F1E7}',
    lat: 51.5,
    lng: -0.1,
    regulation: 'MSN 1768 (M) Ship Medical Stores requirements',
    authority: 'Maritime and Coastguard Agency (MCA)',
    standardKey: 'MCA-MSN1768',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    flag: '\u{1F1F3}\u{1F1F1}',
    lat: 52.4,
    lng: 4.9,
    regulation: 'Decree on Medical Equipment on Board Ships (Besluit Medische Uitrusting)',
    authority: 'Human Environment and Transport Inspectorate (ILT)',
    standardKey: 'ILT-BMU',
  },
  {
    code: 'GR',
    name: 'Greece',
    flag: '\u{1F1EC}\u{1F1F7}',
    lat: 37.9,
    lng: 23.7,
    regulation: 'Medical supplies per Greek maritime legislation aligned with EU directives',
    authority: 'Hellenic Coast Guard',
    standardKey: 'HCG-EU',
  },
  {
    code: 'SG',
    name: 'Singapore',
    flag: '\u{1F1F8}\u{1F1EC}',
    lat: 1.35,
    lng: 103.8,
    regulation: 'Merchant Shipping (Medical Stores) Rules',
    authority: 'Maritime and Port Authority of Singapore (MPA)',
    standardKey: 'MPA-MSR',
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    flag: '\u{1F1ED}\u{1F1F0}',
    lat: 22.3,
    lng: 114.2,
    regulation: 'Medical Scales A & B per MS (Safety) Ordinance',
    authority: 'Hong Kong Marine Department',
    standardKey: 'HKMD-MSO',
  },
  {
    code: 'DK',
    name: 'Denmark',
    flag: '\u{1F1E9}\u{1F1F0}',
    lat: 55.7,
    lng: 12.6,
    regulation: 'Medical chest per Danish Maritime Authority Order',
    authority: 'Danish Maritime Authority (DMA)',
    standardKey: 'DMA-ORDER',
  },
  {
    code: 'IT',
    name: 'Italy',
    flag: '\u{1F1EE}\u{1F1F9}',
    lat: 41.9,
    lng: 12.5,
    regulation: 'Medical supplies per Italian maritime health regulations',
    authority: 'Italian Coast Guard',
    standardKey: 'ICG-REG',
  },
  {
    code: 'DE',
    name: 'Germany',
    flag: '\u{1F1E9}\u{1F1EA}',
    lat: 52.5,
    lng: 13.4,
    regulation: 'Medical stores per Verordnung uber die Krankenfursorge auf Kauffahrteischiffen',
    authority: 'BG Verkehr',
    standardKey: 'BGV-VKKF',
  },
  {
    code: 'CN',
    name: 'China',
    flag: '\u{1F1E8}\u{1F1F3}',
    lat: 39.9,
    lng: 116.4,
    regulation: 'Medical supplies per MSA vessel inspection requirements',
    authority: 'China Maritime Safety Administration (MSA)',
    standardKey: 'MSA-CN',
  },
  {
    code: 'JP',
    name: 'Japan',
    flag: '\u{1F1EF}\u{1F1F5}',
    lat: 35.7,
    lng: 139.7,
    regulation: 'Mariners Act requirements for medical supplies',
    authority: 'Japan Coast Guard / MLIT',
    standardKey: 'JCG-MA',
  },
  {
    code: 'IN',
    name: 'India',
    flag: '\u{1F1EE}\u{1F1F3}',
    lat: 20.6,
    lng: 78.9,
    regulation: 'Medical stores per MS (Medical Examination) Rules',
    authority: 'Directorate General of Shipping (DGS)',
    standardKey: 'DGS-MMER',
  },
  {
    code: 'TR',
    name: 'Turkey',
    flag: '\u{1F1F9}\u{1F1F7}',
    lat: 39.9,
    lng: 32.9,
    regulation: 'Medical chest requirements per Turkish maritime regulations',
    authority: 'General Directorate of Maritime Affairs',
    standardKey: 'GDMA-TR',
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    flag: '\u{1F1E6}\u{1F1EA}',
    lat: 24.5,
    lng: 54.7,
    regulation: 'Medical supplies per UAE Federal Transport Authority standards',
    authority: 'Federal Transport Authority (FTA)',
    standardKey: 'FTA-UAE',
  },
];
